In [61]:
import os
import pandas as pd
import requests
from datetime import datetime
from google.cloud import storage

In [63]:
TRANSACTIONS_PATH = "transactions.xlsb"
CLICKSTREAM_PATH = "clickstream.xlsb"
CHUNK_SIZE = 50000
API_KEY = "8e3ac48efdcca16b9b7c13c0"
API_URL = "https://v6.exchangerate-api.com/v6/8e3ac48efdcca16b9b7c13c0/latest/USD"
##API_URL = "https://api.exchangerate-api.com/v4/latest/USD"   # Example API
BUCKET_NAME = "lsa_storyai_internship2025"
DEST_PREFIX = "cleaned"
BPATH = 'https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025'
tmp = r'C:\tmp'

### Task 1: Explore schemas, nulls, duplicates

In [6]:
def explore_dataset(file_path, name):
    print(f"\n[INFO] Exploring dataset: {name}")
    df = pd.read_excel(file_path, engine="pyxlsb")

    schema = df.dtypes
    nulls = df.isnull().sum()
    dups = df.duplicated().sum()

    print(f"\nSchema for {name}:\n{schema}")
    print(f"\nNull counts for {name}:\n{nulls}")
    print(f"\nDuplicates in {name}: {dups}")

    return df.head(5)

In [8]:
explore_dataset(TRANSACTIONS_PATH, "transactions")

[INFO] Exploring dataset: transactions

Schema for transactions:
txn_id       object
user_id       int64
amount      float64
currency     object
txn_time     object
dtype: object

Null counts for transactions:
txn_id      0
user_id     0
amount      0
currency    0
txn_time    0
dtype: int64

Duplicates in transactions: 0

,txn_id,user_id,amount,currency,txn_time
0,00e22e71-ccc3-4cd8-8b9c-dcd45831360e,30148,69.41,GBP,2025-09-02T17:40:25Z
1,03161627-fa7d-458e-949f-890b227e1f9d,33593,216.51,USD,2025-09-04T05:01:43Z
2,b2ee8412-c2de-4278-9e84-477f3c2608b1,8863,128.51,EUR,2025-09-03T06:22:13Z
3,fd6f9752-3d98-498e-98e6-cec3f2d60c70,15370,133.82,USD,2025-09-04T23:36:06Z
4,1ff86983-6198-4b63-af63-af54d733ae2e,19387,250.94,EUR,2025-09-03T21:37:43Z

In [38]:
explore_dataset(CLICKSTREAM_PATH, "Clickstream")

[INFO] Exploring dataset: Clickstream

Schema for Clickstream:
user_id        int64
session_id    object
page_url      object
click_time    object
device        object
location      object
dtype: object

Null counts for Clickstream:
user_id       0
session_id    0
page_url      0
click_time    0
device        0
location      0
dtype: int64

Duplicates in Clickstream: 0

,user_id,session_id,page_url,click_time,device,location
0,41906,4b8feef4-2332-4867-9612-f6e3d67bb70f,/home,2025-09-02T15:38:39Z,desktop,DE
1,14629,80ddb3a6-7080-4d5b-95d7-0f07296654b2,/product/alpha,2025-09-04T19:27:04Z,mobile,AU
2,5698,cc33cc49-a847-443a-9a8b-7f81f9623c2a,/checkout,2025-09-03T20:32:47Z,mobile,GB
3,14329,0f268ab7-dbd9-47c8-b4a6-4b5a4b39bac1,/product/beta,2025-09-04T02:37:18Z,desktop,AU
4,13032,b79491c9-576c-419c-a5af-6b1b1cf78092,/cart,2025-09-03T20:22:17Z,mobile,ZA

In [10]:
from datetime import datetime
API_KEY = "8e3ac48efdcca16b9b7c13c0"
url = f"https://v6.exchangerate-api.com/v6/{API_KEY}/latest/USD"
response = requests.get(url) 
data = response.json()
today = datetime.today().strftime("%Y-%mmm-%d")
if response.status_code == 200 and data["result"] == "success": 
    rates = data["conversion_rates"] 
    print("USD to INR:", rates["INR"]) 
    print("USD to EUR:", rates["EUR"]) 
    print("USD to GBP:", rates["GBP"]) 
    print("USD to JPY:", rates["JPY"]) 
else: 
    print("API Error:", data)

USD to INR: 88.2133
USD to EUR: 0.853
USD to GBP: 0.7388
USD to JPY: 147.2252

In [13]:
print(rates)

{'USD': 1, 'AED': 3.6725, 'AFN': 68.3283, 'ALL': 82.7218, 'AMD': 382.6216, 'ANG': 1.79, 'AOA': 920.8606, 'ARS': 1418.67, 'AUD': 1.5176, 'AWG': 1.79, 'AZN': 1.7018, 'BAM': 1.6681, 'BBD': 2.0, 'BDT': 121.7538, 'BGN': 1.6678, 'BHD': 0.376, 'BIF': 2970.5923, 'BMD': 1.0, 'BND': 1.2822, 'BOB': 6.9374, 'BRL': 5.4212, 'BSD': 1.0, 'BTN': 88.2145, 'BWP': 13.7197, 'BYN': 3.234, 'BZD': 2.0, 'CAD': 1.3833, 'CDF': 2878.4332, 'CHF': 0.7964, 'CLP': 971.3739, 'CNY': 7.1241, 'COP': 3950.6662, 'CRC': 505.3626, 'CUP': 24.0, 'CVE': 94.0434, 'CZK': 20.7587, 'DJF': 177.721, 'DKK': 6.3674, 'DOP': 63.667, 'DZD': 129.7769, 'EGP': 48.0013, 'ERN': 15.0, 'ETB': 141.6466, 'EUR': 0.853, 'FJD': 2.2395, 'FKP': 0.7387, 'FOK': 6.3673, 'GBP': 0.7388, 'GEL': 2.6924, 'GGP': 0.7387, 'GHS': 12.2074, 'GIP': 0.7387, 'GMD': 72.5163, 'GNF': 8687.1638, 'GTQ': 7.6745, 'GYD': 209.1599, 'HKD': 7.7884, 'HNL': 26.2181, 'HRK': 6.4261, 'HTG': 130.8794, 'HUF': 335.1966, 'IDR': 16460.4362, 'ILS': 3.3447, 'IMP': 0.7387, 'INR': 88.2133, 'IQD': 1307.9512, 'IRR': 42423.4499, 'ISK': 122.1272, 'JEP': 0.7387, 'JMD': 160.2192, 'JOD': 0.709, 'JPY': 147.2252, 'KES': 129.1261, 'KGS': 87.446, 'KHR': 4009.7984, 'KID': 1.5172, 'KMF': 419.5922, 'KRW': 1387.6219, 'KWD': 0.3053, 'KYD': 0.8333, 'KZT': 536.6686, 'LAK': 21709.6601, 'LBP': 89500.0, 'LKR': 302.0352, 'LRD': 199.8836, 'LSL': 17.5258, 'LYD': 5.4103, 'MAD': 9.0101, 'MDL': 16.6424, 'MGA': 4454.5712, 'MKD': 52.6197, 'MMK': 2103.3996, 'MNT': 3567.4386, 'MOP': 8.022, 'MRU': 39.8339, 'MUR': 46.0678, 'MVR': 15.4387, 'MWK': 1742.489, 'MXN': 18.6234, 'MYR': 4.2063, 'MZN': 63.5948, 'NAD': 17.5258, 'NGN': 1506.3857, 'NIO': 36.8122, 'NOK': 9.9771, 'NPR': 141.1432, 'NZD': 1.6863, 'OMR': 0.3845, 'PAB': 1.0, 'PEN': 3.5073, 'PGK': 4.2156, 'PHP': 57.0235, 'PKR': 283.7733, 'PLN': 3.6254, 'PYG': 7159.5773, 'QAR': 3.64, 'RON': 4.3204, 'RSD': 99.8023, 'RUB': 83.5865, 'RWF': 1451.7616, 'SAR': 3.75, 'SBD': 8.2826, 'SCR': 14.6496, 'SDG': 449.0466, 'SEK': 9.3759, 'SGD': 1.2822, 'SHP': 0.7387, 'SLE': 23.2903, 'SLL': 23290.2526, 'SOS': 571.7498, 'SRD': 39.0245, 'SSP': 4550.8829, 'STN': 20.8957, 'SYP': 13107.7234, 'SZL': 17.5258, 'THB': 31.7141, 'TJS': 9.4645, 'TMT': 3.5, 'TND': 2.9033, 'TOP': 2.3606, 'TRY': 41.2689, 'TTD': 6.7717, 'TVD': 1.5172, 'TWD': 30.289, 'TZS': 2473.4492, 'UAH': 41.1554, 'UGX': 3482.1374, 'UYU': 40.0394, 'UZS': 12314.5092, 'VES': 156.3739, 'VND': 26252.5343, 'VUV': 118.6706, 'WST': 2.7465, 'XAF': 559.4562, 'XCD': 2.7, 'XCG': 1.79, 'XDR': 0.7281, 'XOF': 559.4562, 'XPF': 101.7765, 'YER': 240.0213, 'ZAR': 17.5264, 'ZMW': 24.1148, 'ZWL': 26.7103}

### Task 3: Transform

In [15]:
def process_chunk(chunk, rates):
    # Standardize column names
    chunk.columns = [col.strip().lower().replace(" ", "_") for col in chunk.columns]
 # Convert timestamps
    if "txn_time" in chunk.columns:
        chunk["txn_time"] = pd.to_datetime(chunk["txn_time"], utc=True)
    else: 
        chunk["click_time"] = pd.to_datetime(chunk["click_time"], utc = True)

    # Deduplicate
    chunk = chunk.drop_duplicates()

    # Enrich transactions
    if "currency" in chunk.columns and "amount" in chunk.columns:
        chunk["amount_in_usd"] = chunk.apply(
            lambda row: row["amount"] / rates.get(row["currency"], 1)
            if pd.notnull(row["amount"]) else None,
            axis=1
        )

    return chunk

In [17]:
print(TRANSACTIONS_PATH)

transactions.xlsb

In [19]:
all_chunks = []
for chunk in pd.read_csv("transactions.csv", chunksize=50000):
    all_chunks.append(process_chunk(chunk, rates))

df_transactions = pd.concat(all_chunks, ignore_index=True)

In [21]:
df_transactions

,txn_id,user_id,amount,currency,txn_time,amount_in_usd
0,00e22e71-ccc3-4cd8-8b9c-dcd45831360e,30148,69.41,GBP,2025-09-02 17:40:25+00:00,93.949648
1,03161627-fa7d-458e-949f-890b227e1f9d,33593,216.51,USD,2025-09-04 05:01:43+00:00,216.510000
2,b2ee8412-c2de-4278-9e84-477f3c2608b1,8863,128.51,EUR,2025-09-03 06:22:13+00:00,150.656506
3,fd6f9752-3d98-498e-98e6-cec3f2d60c70,15370,133.82,USD,2025-09-04 23:36:06+00:00,133.820000
4,1ff86983-6198-4b63-af63-af54d733ae2e,19387,250.94,EUR,2025-09-03 21:37:43+00:00,294.185229
...,...,...,...,...,...,...
99995,fa182022-f693-4873-818a-3ce4129ff3bb,42858,71.65,GBP,2025-09-03 16:43:28+00:00,96.981592
99996,704da747-2d29-4a13-a317-6b7ac489ef8d,37737,99.33,USD,2025-09-05 13:39:06+00:00,99.330000
99997,e62819e4-01e9-4da4-8c66-cc0628fb0328,41423,109.23,EUR,2025-09-04 13:07:43+00:00,128.053927
99998,20cd9933-b80d-4318-aa24-85d9f1758406,2402,33087.96,JPY,2025-09-04 21:13:27+00:00,224.743862
99999,6f511f29-5bfd-442f-a0ee-ea4ba6429764,13863,108.84,GBP,2025-09-04 05:07:58+00:00,147.319978

In [23]:
all_chunks = []
for chunk in pd.read_csv("clickstream.csv", chunksize=50000):
    all_chunks.append(process_chunk(chunk, rates))

df_clickstream= pd.concat(all_chunks, ignore_index=True)

In [25]:
df_clickstream.head()

,user_id,session_id,page_url,click_time,device,location
0,41906,4b8feef4-2332-4867-9612-f6e3d67bb70f,/home,2025-09-02 15:38:39+00:00,desktop,DE
1,14629,80ddb3a6-7080-4d5b-95d7-0f07296654b2,/product/alpha,2025-09-04 19:27:04+00:00,mobile,AU
2,5698,cc33cc49-a847-443a-9a8b-7f81f9623c2a,/checkout,2025-09-03 20:32:47+00:00,mobile,GB
3,14329,0f268ab7-dbd9-47c8-b4a6-4b5a4b39bac1,/product/beta,2025-09-04 02:37:18+00:00,desktop,AU
4,13032,b79491c9-576c-419c-a5af-6b1b1cf78092,/cart,2025-09-03 20:22:17+00:00,mobile,ZA

#### Task 4: Load — write cleaned outputs to GCS paths partitioned by ingest_date=YYYY-MM-DD/ for each dataset.

In [65]:
def upload_to_gcs(df, bucket_name, prefix, dataset_name):
    client = storage.Client(project="winter-agility-471714-p2")
    bucket = client.bucket(bucket_name)

    ingest_date = datetime.utcnow().strftime("%Y-%m-%d")
    dest_path = f"{BPATH}/{prefix}/{dataset_name}/ingest_date={ingest_date}/{dataset_name}.parquet"

    tmp_file = f"/tmp1/{dataset_name}.parquet"
    df.to_parquet(tmp_file, index=False)
    blob = bucket.blob(dest_path)
    blob.upload_from_filename(tmp_file)
    print(f"[SUCCESS] Uploaded {dataset_name} → gs://{bucket_name}/{dest_path}")

In [85]:
all_chunks = []
for chunk in pd.read_csv("transactions.csv", chunksize=50000):
    all_chunks.append(process_chunk(chunk, rates))
    upload_to_gcs(df_transactions, BUCKET_NAME, DEST_PREFIX, "transactions")

df_transactions = pd.concat(all_chunks, ignore_index=True)

C:\Users\sures\AppData\Local\Temp\ipykernel_9992\4132863977.py:5: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ingest_date = datetime.utcnow().strftime("%Y-%m-%d")

[SUCCESS] Uploaded transactions → gs://lsa_storyai_internship2025/https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025/cleaned/transactions/ingest_date=2025-09-10/transactions.parquet

C:\Users\sures\AppData\Local\Temp\ipykernel_9992\4132863977.py:5: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ingest_date = datetime.utcnow().strftime("%Y-%m-%d")

[SUCCESS] Uploaded transactions → gs://lsa_storyai_internship2025/https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025/cleaned/transactions/ingest_date=2025-09-10/transactions.parquet

In [71]:
all_chunks = []
for chunk in pd.read_csv("clickstream.csv", chunksize=50000):
    all_chunks.append(process_chunk(chunk, rates))
    upload_to_gcs(df_clickstream, BUCKET_NAME, DEST_PREFIX, "clickstream")

df_transactions = pd.concat(all_chunks, ignore_index=True)

C:\Users\sures\AppData\Local\Temp\ipykernel_9992\4132863977.py:5: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ingest_date = datetime.utcnow().strftime("%Y-%m-%d")

[SUCCESS] Uploaded clickstream → gs://lsa_storyai_internship2025/https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025/cleaned/clickstream/ingest_date=2025-09-10/clickstream.parquet

C:\Users\sures\AppData\Local\Temp\ipykernel_9992\4132863977.py:5: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ingest_date = datetime.utcnow().strftime("%Y-%m-%d")

[SUCCESS] Uploaded clickstream → gs://lsa_storyai_internship2025/https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025/cleaned/clickstream/ingest_date=2025-09-10/clickstream.parquet

C:\Users\sures\AppData\Local\Temp\ipykernel_9992\4132863977.py:5: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ingest_date = datetime.utcnow().strftime("%Y-%m-%d")

[SUCCESS] Uploaded clickstream → gs://lsa_storyai_internship2025/https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025/cleaned/clickstream/ingest_date=2025-09-10/clickstream.parquet

C:\Users\sures\AppData\Local\Temp\ipykernel_9992\4132863977.py:5: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  ingest_date = datetime.utcnow().strftime("%Y-%m-%d")

[SUCCESS] Uploaded clickstream → gs://lsa_storyai_internship2025/https://console.cloud.google.com/storage/browser/dataengg_intershipsep2025/cleaned/clickstream/ingest_date=2025-09-10/clickstream.parquet

#### Task 5: Logging & alerts — log record counts and failures; print warnings if inputs are missing or API fails.

In [75]:
def log_summary(df, name):
    print(f"[SUMMARY] {name}: {len(df)} records after cleaning.")

In [87]:
log_summary(df_transactions, "transactions")
log_summary(df_clickstream, "clickstream")

[SUMMARY] transactions: 100000 records after cleaning.
[SUMMARY] clickstream: 200000 records after cleaning.